### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by pavlo888** [SWittouck/progenomics#7]
Hi everyone, 

Congratulations on the new release of the package! I am eager to try it out; however, I believe there is an installation explanation missing. How can I install the package? I have successfully installed all the dependencies already. 

Thank you very much for your support. 

Cheers, 
Pablo

**Comment by SWittouck** [comment]
Hi Pablo, 

Thanks for your interest in the new version! 

If the dependencies are successfully installed, you should be able to run the script `src/progenomics/progenomics.py`. If you want to be able to run the tool by just calling the command `progenomics`, there are various ways to achieve that: 

* You can create a symbolic link in a directory that is in your PATH. For example, you could try `ln -s $PATH_TO_PROGENOMICS/src/progenomics/progenomics.py ~/bin/progenomics`
* You can create an alias by adding the following line to the file `~/.bashrc`: `progenomics=$PATH_TO_PROGENOMICS/src/progenomics/progenomics.py`

Let me know if this works! 

Stijn

**Comment by pavlo888** [comment]
Hi Stijn, 

Thank you for your answer. 

I have tried to directly run the script but I get an error: 

(progenomics2020) sam@BioInf2:/home$ '/home/sam/Downloads/progenomics-0.2.0/src/progenomics/progenomics.py' 
Traceback (most recent call last):
  File "/home/sam/Downloads/progenomics-0.2.0/src/progenomics/progenomics.py", line 13, in <module>
    from tasks import *
  File "/home/sam/Downloads/progenomics-0.2.0/src/progenomics/tasks.py", line 13, in <module>
    from checkers import *
  File "/home/sam/Downloads/progenomics-0.2.0/src/progenomics/checkers.py", line 6, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

Do you know what could be possible going wrong? 

Cheers, 
Pablo

**Comment by SWittouck** [comment]
Hi Pablo, 

It seems like biopython is not (properly) installed. Can you install it by running `pip3 install biopython` and then try again? 

Stijn

**Comment by pavlo888** [comment]
Hi Stijn, 

I have finally managed installing all the dependencies with pip3. However, when I try to run the pipeline with 4 .faa files, I get the following error: 

  File "/home/sam/Downloads/progenomics-0.2.0/src/progenomics/progenomics.py", line 222, in <module>
    args.func(args)
  File "/home/sam/Downloads/progenomics-0.2.0/src/progenomics/tasks.py", line 394, in run_core_pipeline
    seedpaths = sample(faapaths, args.seeds)
  File "/home/sam/anaconda2/envs/progenomics2020/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

Do you have any idea what am I doing wrong? 

Cheers, 
Pablo

**Comment by SWittouck** [comment]
Hi Pablo, 

The problem is that progenomics takes 50 seed genomes by default, which is of course hard when you only have four genomes. You should be able to fix this by adding the options `-e 4 -f 3`. This will make progenomics use all four genomes as seeds and require candidate core genes to be present in three out of four seed genomes. 

Let me know if this works,

Stijn
